cabal-version:      3.0
name:               raytracer
version:            0.1.0.0
synopsis:           Simple raytracer written in Haskell
description:        Simple raytracer written in Haskell
license:            MIT
license-file:       LICENSE
author:             Preston Corless
maintainer:         pgattic@gmail.com

-- A copyright notice.
-- copyright:

build-type:         Simple
extra-doc-files:    README.md

-- Extra source files to be distributed with the package, such as examples, or a tutorial module.
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    hs-source-dirs:   src
    exposed-modules:  Camera, Color, Image, Interval, Point3, Ray, Renderer, Scene, Vec3,
                      Hittables.HitRecord,
                      Hittables.Hittable,
                      Hittables.Sphere
    import:           warnings
    build-depends:    base ^>=4.20.2.0
    default-language: Haskell2010

executable raytracer
    hs-source-dirs:   app
    main-is:          Main.hs
    import:           warnings
    build-depends:    base ^>=4.20.2.0, raytracer
    default-language: Haskell2010
